language: ruby
dist: xenial
rvm:
  - 3.0.0
  - 2.5.0
matrix:
  include:
    # OS X 10.9.5-10.10.0 (2.0.0-p481)
    - rvm: 2.0.0-p481
      dist: trusty

#addons:
# code_climate:
#   repo_token: #TODO

bundler_args: --without=documentation

before_install:
  - gem install bundler -v "~> 1.17"
  - if [[ "$TRAVIS_RUBY_VERSION" = 3.* ]]; then gem install bundler -v "~> 2.0" && bundle update --bundler && bundle update rake; fi

script: bundle exec rake spec
