language: ruby
rvm:
  - 2.5.0
  # OS X 10.9.5-10.10.0 (2.0.0-p481)
  - 2.0.0-p481
  # OS X 10.9.3-10.9.4
  - 2.0.0-p451


#addons:
# code_climate:
#   repo_token: #TODO

bundler_args: --without=documentation

script: bundle exec rake spec
