#addons:
# code_climate:
#   repo_token: #TODO

env:
  - RVM_RUBY_VERSION=system
  - RVM_RUBY_VERSION=1.8.7-p358

install:
  - bundle install --without=documentation --path ./travis_bundle_dir

script: rake spec
